version: '3'
services:

  nginx:
    image: nginx
    ports:
      - 8080:80
      - 8081:81
    volumes:
      - ./nginx/conf.d/metrics.conf:/etc/nginx/conf.d/metrics.conf
    restart: always

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter
    ports:
      - 9113:9113
    command:
      - -nginx.scrape-uri=http://nginx:81/metrics
    restart: always
    depends_on:
      - nginx

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always
    depends_on:
      - nginx-exporter

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana/datasources/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    restart: always
    depends_on:
      - prometheus
